---
  swagger: "2.0"
  info: 
    version: "1.0.0"
    title: "Provider Data System"
    description: "An API that interacts with a SQL database backend of medical provider data system."
    contact: 
      name: "Scott Steinbruegge"
  host: "localhost:8080"
  basePath: "/PDS"
  schemes: 
    - "http"
  consumes: 
    - "application/json"
  produces: 
    - "application/json"
  paths: 
    /provider: 
      get: 
        description: "Returns all medical providers in the system."
        operationId: "getProviders"
        responses: 
          200:
            description: "A list of all medical providers."
            schema: 
              type: "array"
              items:
                $ref: "#/definitions/Provider"
          400:
            $ref: '#/responses/400Error'
      post:
        description: "User can insert a new provider record."
        operationId: "createProvider"
        parameters:
          - name: provider
            in: body
            description: "Creates a new medical provider record."
            schema:
              $ref: '#/definitions/Provider'
        responses:
          200:
            description: Successfully created a new artist
          400:
            $ref: '#/responses/400Error'

    /provider/{npi}:
      get:
        description: "Returns medical provider of the speicifed provider NPI"
        operationId: "getProvider"
        parameters: 
          - name: "npi"
            in: "path"
            description: "Provider type of providers to return"
            required: true
            type: "integer"        
        responses :
          200:
            description: "Providers with the specified provider type."
            schema: 
              type: "array"
              items:
                $ref: "#/definitions/Provider"
          400:
            $ref: '#/responses/400Error'
      patch:
        description: "Update a providers information based on NPI supplied"
        operationId: "updateProvider"
        parameters: 
          - name: "npi"
            in: "path"
            description: "Provider type of providers to return"
            required: true
            type: "integer"
        responses:
          200:
            description: "Returns the updated provider data."
            schema: 
              type: "array"
              items:
                $ref: "#/definitions/Provider"
          400:
            $ref: '#/responses/400Error'
      delete: 
        description: "Delete a single provider based on NPI supplied."
        operationId: "deleteProvider"
        parameters: 
          - name: "npi"
            in: "path"
            description: "NPI of provider to delete"
            required: true
            type: "integer"
        responses: 
          204:
            description: "Provider deleted"
          400:
            $ref: '#/responses/400Error'

  definitions: 
    Provider: 
      type: "object"
      required: 
        - "npi"
        - "provider_type"
        - "ssn"
      properties: 
        npi: 
          type: "integer"
        provider_type: 
          type: "string"
        first_name: 
          type: "string"
        last_name:
          type: "string"
        ssn:
          type: "integer"
  responses:
    400Error:
      description: Invalid request
      schema:
        type: object 
        properties:
          message:
            type: string
      
          
        
          
