# coding: utf-8

"""
    Provider Data System

    An API that interacts with a SQL database backend of medical provider data system.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response_400 import InlineResponse400  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse400(unittest.TestCase):
    """InlineResponse400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse400(self):
        """Test InlineResponse400"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response_400.InlineResponse400()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
