cloudmesh:
  aws-data-services:
    mysql:
      user:
        name: "IUuser"
        password: "Password123"
    redshift:
      user:
        name: "iuuser"
        password: "Password123"
    misc:
      k1: "AKIAI7SSZUJAJEPBPE2Q"
      k2: "83gI2as1wkP17IKs/qKfI1rO8o6Dq/o6GpzKPHU+"
